version: '3'
services:
  web:
    build: .
    command: gunicorn triage_ai.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: triage
      POSTGRES_USER: triage
      POSTGRES_PASSWORD: triage
